// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5Vyg_68qfcCsKzap9FuIsXKqIjeMi6U',
    appId: '1:110365860900:web:99ead80b1ff2bef87c64b1',
    messagingSenderId: '110365860900',
    projectId: 'splitwise-pro-flutter-app',
    authDomain: 'splitwise-pro-flutter-app.firebaseapp.com',
    storageBucket: 'splitwise-pro-flutter-app.appspot.com',
    measurementId: 'G-F106CVZ697',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbSy-K13MwjSdobELoDW_wS6ktRzZpl0',
    appId: '1:110365860900:android:7c1d813dcc26aa927c64b1',
    messagingSenderId: '110365860900',
    projectId: 'splitwise-pro-flutter-app',
    storageBucket: 'splitwise-pro-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN31Zlu-CwH3x9iBnXE6r6-v1yGTIfKBI',
    appId: '1:110365860900:ios:a2284c3854d39be57c64b1',
    messagingSenderId: '110365860900',
    projectId: 'splitwise-pro-flutter-app',
    storageBucket: 'splitwise-pro-flutter-app.appspot.com',
    iosBundleId: 'com.example.splitwisePro',
  );
}
